BIN_PATH=/usr/local/bin
CLUSTER_HOST=127.0.0.1
CONTAINER_IP=`hostname -I`
PORT=30000
# NODES=$(cat /proc/cpuinfo| grep cores | wc -l)
NODES=16
REPLICAS=1
PROTECTED_MODE=no
ADDITIONAL_OPTIONS="--save "" --appendonly no --cluster-announce-ip $CONTAINER_IP --cluster-node-timeout 30000 --proto-max-bulk-len 2048mb --loadmodule /var/opt/redislabs/lib/modules/redisgears.so Plugin /var/opt/redislabs/modules/rg/plugin/gears_python.so PythonInstallationDir /var/opt/redislabs/modules/rg CreateVenv 1 DownloadDeps 1 "
